[project]
name = "classification"
version = "0.1.1"
description = "Training logic for a convolutional neural network."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "torch",
  "torchvision",
  "tensorboard",
  "tqdm"
]